### ISSUE TITLE
Installing plugin from the community plugins page immediately fails.

### ISSUE THREAD

**Issue by wychwitch** [fantasycalendar/obsidian-fantasy-calendar#3]
I'm not sure what the issue is? If I hit the install button it immediately says it fails to install. I deleted the folder I had installed manually and tried again and I had the same result. Even on mobile where I haven't installed it at all before I ran into this issue. Maybe something isn't formatted right?

**Comment by WychWitch** [comment]
Yep it works!! Thank you that was real fast ^^
