### ISSUE TITLE
Unable to Add Condition in Leap Days Configuration

### ISSUE THREAD

**Issue by PureDevr** [fantasycalendar/obsidian-fantasy-calendar#53]
When I am configuring Leap Days, I cannot add conditions by clicking the "+" button.
![image](https://user-images.githubusercontent.com/100462341/160237101-f3b7c142-8dff-4e05-a74f-31158952a2ba.png)

In a Gregorian Calendar preset, I can see the three conditions. Yet, I also can't add new ones by the "+" button.
![image](https://user-images.githubusercontent.com/100462341/160237105-7a266c02-ad2d-4232-a2a1-d0011774030d.png)

There are no errors in the console.
(Reported this issue in _#plugin-general_ in Obsidian Members Group Discord and _#calendar-obsidian_ in Fantasy Computerwork Discord.

**Comment by PureDevr** [comment]
🗿 After I closed the console seconds ago, it seems like the condition configuration window pops out. However, the entire screen is misaligned. Therefore I believe this is a front end issue. **The configuration window did pop out, but it is at somewhere inaccessible.**
![image](https://user-images.githubusercontent.com/100462341/160237231-faf7f9da-cbf2-4fdf-bb1b-28d243d5c5ba.png)

**Comment by valentine195** [comment]
This is fixed in [v2.3.3](https://github.com/fantasycalendar/obsidian-fantasy-calendar/releases/tag/2.3.3)
