### ISSUE TITLE
Feature Request: Add "Go To Day" menu item

### ISSUE THREAD

**Issue by namtrah** [fantasycalendar/obsidian-fantasy-calendar#58]
I need to switch to previous years, months, days and the UI is not made for that. Would there be a way to add a menu item "Go To Day" (not "Go today") ;) so that I can pick a random date yyyy-mm-dd in the past/future and FC will jump to it?

Use case is setting Birthdays events on the original day. Not the current date.

**Comment by valentine195** [comment]
This can be done by clicking the settings button on the calendar view and clicking "View Day"
